scoreboard objectives add rng dummy rng
scoreboard players random @s rng 1 59

execute @s[scores={rng=1}] ~~~ summon minecraft:bat
execute @s[scores={rng=2}] ~~~ summon minecraft:cat
execute @s[scores={rng=3}] ~~~ summon minecraft:chicken
execute @s[scores={rng=4}] ~~~ summon minecraft:cod
execute @s[scores={rng=5}] ~~~ summon minecraft:cow
execute @s[scores={rng=6}] ~~~ summon minecraft:donkey
execute @s[scores={rng=7}] ~~~ summon minecraft:fox
execute @s[scores={rng=8}] ~~~ summon minecraft:horse
execute @s[scores={rng=9}] ~~~ summon minecraft:mooshroom
execute @s[scores={rng=10}] ~~~ summon minecraft:mule
execute @s[scores={rng=11}] ~~~ summon minecraft:ocelot
execute @s[scores={rng=12}] ~~~ summon minecraft:parrot
execute @s[scores={rng=13}] ~~~ summon minecraft:pig
execute @s[scores={rng=14}] ~~~ summon minecraft:pufferfish
execute @s[scores={rng=15}] ~~~ summon minecraft:rabbit
execute @s[scores={rng=16}] ~~~ summon minecraft:salmon
execute @s[scores={rng=17}] ~~~ summon minecraft:sheep
execute @s[scores={rng=18}] ~~~ summon minecraft:skeleton_horse
execute @s[scores={rng=19}] ~~~ summon minecraft:snow_golem
execute @s[scores={rng=20}] ~~~ summon minecraft:strider
execute @s[scores={rng=21}] ~~~ summon minecraft:squid
execute @s[scores={rng=22}] ~~~ summon minecraft:tropicalfish
execute @s[scores={rng=23}] ~~~ summon minecraft:turtle
execute @s[scores={rng=24}] ~~~ summon minecraft:villager
execute @s[scores={rng=25}] ~~~ summon minecraft:wandering_trader
execute @s[scores={rng=26}] ~~~ summon minecraft:bee
execute @s[scores={rng=27}] ~~~ summon minecraft:cave_spider
execute @s[scores={rng=28}] ~~~ summon minecraft:dolphin
execute @s[scores={rng=29}] ~~~ summon minecraft:enderman
execute @s[scores={rng=30}] ~~~ summon minecraft:llama
execute @s[scores={rng=31}] ~~~ summon minecraft:piglin
execute @s[scores={rng=32}] ~~~ summon minecraft:polar_bear
execute @s[scores={rng=33}] ~~~ summon minecraft:panda
execute @s[scores={rng=34}] ~~~ summon minecraft:spider
execute @s[scores={rng=35}] ~~~ summon minecraft:wolf
execute @s[scores={rng=36}] ~~~ summon minecraft:zombie_pigman
execute @s[scores={rng=37}] ~~~ summon minecraft:blaze
execute @s[scores={rng=38}] ~~~ summon minecraft:creeper
execute @s[scores={rng=39}] ~~~ summon minecraft:drowned
execute @s[scores={rng=40}] ~~~ summon minecraft:endermite
execute @s[scores={rng=42}] ~~~ summon minecraft:guardian
execute @s[scores={rng=43}] ~~~ summon minecraft:hoglin
execute @s[scores={rng=44}] ~~~ summon minecraft:husk
execute @s[scores={rng=45}] ~~~ summon minecraft:magma_cube
execute @s[scores={rng=46}] ~~~ summon minecraft:phantom
execute @s[scores={rng=48}] ~~~ summon minecraft:pillager
execute @s[scores={rng=49}] ~~~ summon minecraft:shulker
execute @s[scores={rng=50}] ~~~ summon minecraft:silverfish
execute @s[scores={rng=51}] ~~~ summon minecraft:skeleton
execute @s[scores={rng=52}] ~~~ summon minecraft:slime
execute @s[scores={rng=53}] ~~~ summon minecraft:stray
execute @s[scores={rng=54}] ~~~ summon minecraft:vex
execute @s[scores={rng=55}] ~~~ summon minecraft:vindicator
execute @s[scores={rng=56}] ~~~ summon minecraft:witch
execute @s[scores={rng=57}] ~~~ summon minecraft:wither_skeleton
execute @s[scores={rng=58}] ~~~ summon minecraft:zoglin
execute @s[scores={rng=59}] ~~~ summon minecraft:zombie
execute @s[scores={rng=41}] ~~~ summon minecraft:zombie_villager
execute @s[scores={rng=47}] ~~~ summon minecraft:zombie_horse

tp @s ~ -100 ~